### ISSUE TITLE
Chore: add linting to the server

### ISSUE THREAD

**Issue by takanome-dev** [takanome-dev/blog-with-astro-golang#40]
### Type of feature

📦 Chore

### Current behavior

There is no linting in the server

### Suggested solution

Use https://github.com/golangci/golangci-lint for linting the Go web server

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by abdulbari149** [comment]
Hi, I have just started working with Go. Would love to implement it. Please let me know about it

**Comment by takanome-dev** [comment]
@abdulbari149 sure, feel free to take it up. Give the [contributing guide](https://github.com/takanome-dev/blog-with-astro-golang/blob/main/CONTRIBUTING.md#bugs-and-issues) a read to assign yourself and the readme to get up and running. Let me know if you hit any issues
