### ISSUE TITLE
Chore: add code of conduct file 

### ISSUE THREAD

**Issue by takanome-dev** [takanome-dev/blog-with-astro-golang#44]
### Type of feature

📦 Chore

### Current behavior

This repo does not have a code of conduct file

### Suggested solution

Create a new file named `CODE_OF_CONDUCT.md` and use the content of https://www.contributor-covenant.org/version/2/1/code_of_conduct/

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Madhvik007** [comment]
Assign this to me. I can do this
